---
- hosts: all

  vars_files:
  - ./config.yaml

  roles:
  - { role: win_setup, when: win_setup }
  - { role: silence-sensu, when: sensu_silence }
  - { role: win_updates, when: win_update }
  - { role: win_serices, when: win_services }