---
- hosts: all

  vars_files:
  - ./config.yaml

  roles:
  - { role: win-setup, when: win_setup }
  - { role: silence-sensu, when: sensu_silence }
  - { role: win-updates, when: win_update }
  - { role: win-services, when: win_services }