#- name: configure ansible user
#  win_user:
#    name: "{{ ansible_user }}"
#    fullname: "{{ ansible_user_fname }}"
#    password: "{{ ansible_pw }}"
#    password_expired: no
#    password_never_expires: yes
#    user_cannot_change_password: no
#    state: present
#    groups:
#    - "{{ ansible_user_group }}"
- name: check for chocolatey
  win_file:
    path: c:\ProgramData\chocolatey
    state: directory
  register: status_choco
- name: install chocolatey
  win_shell: "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
  when: status_choco|changed