- name: ensure all relevant services are started
  win_service:
    name: "{{ item }}"
    state: started
  with_items:
  - "{{ win_services_host_specific }}"
  - "{{ win_services_defaults }}"
